In [4]:
import numpy as np

In [5]:
dmt_losses = np.load('dmt_loss.npy')
plabel_losses = np.load('plabel_loss.npy')
baseline_losses = np.load('baseline_loss.npy')

In [6]:
dmt_losses, plabel_losses

(array([0.62268513, 0.66644037, 0.77886093, 0.81881487, 0.87945276,
        0.88411725, 0.87821257]),
 array([0.62777567, 0.6780839 , 0.75154734, 0.81312442, 0.87581766,
        0.88615638, 0.88993001]))

In [12]:
baseline_losses.reshape(7,5).mean(1)

array([0.58134027, 0.64341052, 0.75509907, 0.79863341, 0.87233567,
       0.88466622, 0.88779955])

In [13]:
baselines = baseline_losses.reshape(7,5)

In [14]:
baselines_mean, baselines_std = baselines.mean(1), baselines.std(1)

In [16]:
baselines_mean, baselines_std

(array([0.58134027, 0.64341052, 0.75509907, 0.79863341, 0.87233567,
        0.88466622, 0.88779955]),
 array([0.00943668, 0.02304353, 0.0053193 , 0.00537976, 0.00143342,
        0.00199367, 0.00253086]))

In [17]:
label_props =  [0.01, 0.02, 0.05, 0.1, 0.5, 0.8, 1.0]


In [19]:
from collections import defaultdict

In [ ]:
results_dict = defaultdict(label_props, [baselines_mean, ])